apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'expo-module-gradle-plugin'

group = 'com.vaultix.autofill'
version = '0.1.0'

android {
  namespace 'com.vaultix.autofill'
  defaultConfig {
    minSdkVersion 26
    versionCode 1
    versionName "0.1.0"
  }
}

dependencies {
  implementation 'androidx.security:security-crypto:1.1.0-alpha06'
}
